import Head from "next/head";
import React from "react";
/*import ComputerWindow from "@/components/ComputerWindow";*/
import styles from "@/styles/Home.module.css";
import {Inter} from "next/font/google";
/*import { Container } from "react-bootstrap";*/
/*import slideshow from '../../assets/img/events/wcs google workshop.png';
import Image from "next/image"; */
import Carousel from "@/components/carousel";
import StayInTouchSection from "@/components/StayInTouchSection";
import UpcomingEventsSection from "@/components/UpcomingEventsSection";
import AboutUsSection from "@/components/AboutUsSection";

const inter = Inter({subsets: ["latin"]});

export default function Home() {
  return (
    <>
      <Head>
        <title>WCS @ UIUC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <h1>Illinois Women in Computer Science</h1>
        <Carousel />
        <AboutUsSection />
        <UpcomingEventsSection />
        <StayInTouchSection />
      </main>
    </>
  );
}
