import Head from "next/head";
import Link from "next/link";
import React from "react";
import {Button} from "react-bootstrap";
import ComputerWindow from "@/components/ComputerWindow";
import EventsWindow from "@/components/EventsWindow";
import UpcomingEvent from "@/components/UpcomingEvent";
import styles from "@/styles/Home.module.css";
import {Inter} from "next/font/google";
import Layout from "@/components/layout";
import UpcomingEventsSection from "@/components/UpcomingEventsSection";
import PhoneComponent from "@/components/PhoneComponent";
import AboutUsSection from "@/components/AboutUsSection";

const inter = Inter({subsets: ["latin"]});

export default function Home() {
  return (
    <>
      <Head>
        <title>WCS @ UIUC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <h1>Illinois Women in Computer Science</h1>
        <div className={`${styles.windowContainer}`}>
          <ComputerWindow>
            <div className={`${styles.windowImageContainer}`}>
              <img
                src="assets/img/members/committees23-24.jpg"
                className={`${styles.windowImage}`}
              ></img>
            </div>
          </ComputerWindow>
        </div>
        <AboutUsSection />
        <UpcomingEventsSection />
      </main>
    </>
  );
}
